# Generated by Django 4.1.2 on 2022-10-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="date_released",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="song",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
