# Generated by Django 4.1.2 on 2022-10-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicapp", "0002_alter_song_date_released_alter_song_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lyric",
            name="content",
            field=models.TextField(max_length=1000),
        ),
    ]
