# Generated by Django 4.1 on 2022-10-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("musicapp", "0003_alter_lyric_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lyric",
            old_name="content",
            new_name="lyric",
        ),
    ]
